### ISSUE TITLE
运行main.py

### ISSUE THREAD

**Issue by wx227** [fentensoft/wangka_numpool#2]
你好大神，我是小白，琢磨了 四个小时了，你说的我都装了，但是怎么运行main,py 啊，网上的方法我都试了都不行啊 

(py_ven_flask) C:\Users\wx227\Desktop\py_ven_flask\Scripts>python main.py
  File "main.py", line 7
    <!DOCTYPE html>
    ^

**Comment by fentensoft** [comment]
你好，请提供一下完整的错误日志，下面几行也需要

**Comment by wx227** [comment]
刚才是我搞错了，从github右键直接下载的有问题，我重新下了一份main.py 但是运行的时候 还是有报错

C:\Users\wx227>python C:\Users\wx227\Desktop\main.py
Traceback (most recent call last):
  File "C:\Users\wx227\Desktop\main.py", line 8, in <module>
    from worker import Worker, getDistrictCode, product_list
ModuleNotFoundError: No module named 'worker'

**Comment by fentensoft** [comment]
要先进入这个目录再运行Python:
`
cd C:\Users\wx227\Desktop\
`
`
python main.py
`
